/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#0f131c",
        "inverse-on-surface": "#2c303a",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-container": "#340080",
        "on-tertiary-fixed-variant": "#653e00",
        "on-surface-variant": "#cbc3d7",
        "secondary-container": "#03b5d3",
        "hazard-crimson": "#ef4444",
        "surface-overlay": "#2a3040",
        "on-secondary-container": "#00424e",
        "on-tertiary-container": "#3e2400",
        "on-secondary-fixed": "#001f26",
        "surface-container-low": "#181b25",
        "surface": "#0f131c",
        "tertiary": "#ffb95f",
        "surface-card": "#222734",
        "tertiary-container": "#ca8100",
        "surface-deck": "#181c25",
        "on-tertiary": "#472a00",
        "text-secondary": "#94a3b8",
        "secondary": "#4cd7f6",
        "primary-fixed-dim": "#d0bcff",
        "outline": "#958ea0",
        "primary-fixed": "#e9ddff",
        "primary-container": "#a078ff",
        "surface-base": "#0f131c",
        "border-active": "#3b4356",
        "secondary-fixed": "#acedff",
        "on-primary-fixed-variant": "#5516be",
        "on-error": "#690005",
        "inverse-surface": "#dfe2ef",
        "error-container": "#93000a",
        "border-subtle": "#252b3b",
        "on-background": "#dfe2ef",
        "on-primary-fixed": "#23005c",
        "error": "#ffb4ab",
        "vitality-emerald": "#10b981",
        "on-tertiary-fixed": "#2a1700",
        "text-primary": "#f1f5f9",
        "inverse-primary": "#6d3bd7",
        "surface-variant": "#31353f",
        "on-surface": "#dfe2ef",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#0a0e17",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "on-primary": "#3c0091",
        "outline-variant": "#494454",
        "text-muted": "#64748b",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-bright": "#353943",
        "surface-dim": "#0f131c",
        "primary": "#d0bcff",
        "surface-tint": "#d0bcff",
        "tertiary-fixed": "#ffddb8",
        "surface-container": "#1c2029",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003640"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2rem",
        "space-sm": "0.5rem",
        "gutter": "1rem",
        "margin": "1rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-xl": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-rpg": [ "Rajdhani", "sans-serif" ],
        "headline-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-ui": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "stat-display": [ "Rajdhani", "sans-serif" ],
        "label-rpg-sm": [ "Rajdhani", "sans-serif" ],
        "stat-display-sm": [ "Rajdhani", "sans-serif" ],
        "headline-xl-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-md": [ "Plus Jakarta Sans", "sans-serif" ]
      },
      fontSize: {
        "headline-lg-mobile": [ "24px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" } ],
        "headline-xl": [ "40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" } ],
        "label-rpg": [ "13px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" } ],
        "headline-lg": [ "28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "700" } ],
        "headline-sm": [ "16px", { "lineHeight": "24px", "letterSpacing": "-0.005em", "fontWeight": "600" } ],
        "label-ui": [ "12px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "500" } ],
        "headline-md": [ "20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" } ],
        "stat-display": [ "32px", { "lineHeight": "34px", "letterSpacing": "0.02em", "fontWeight": "700" } ],
        "label-rpg-sm": [ "11px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "600" } ],
        "stat-display-sm": [ "20px", { "lineHeight": "22px", "letterSpacing": "0.03em", "fontWeight": "600" } ],
        "headline-xl-mobile": [ "30px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "700" } ],
        "body-sm": [ "12px", { "lineHeight": "16px", "letterSpacing": "0.005em", "fontWeight": "400" } ],
        "body-lg": [ "16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" } ],
        "body-md": [ "14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" } ]
      }
    },
  },
  plugins: [],
}
