"""Add onboarding fields and update character

Revision ID: 88ff7fc815eb
Revises: 859fc09ee446
Create Date: 2026-09-12 23:47:41.043272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ff7fc815eb'
down_revision: Union[str, None] = '859fc09ee446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('adventure_path', sa.String(), nullable=True))
    op.drop_column('characters', 'pathName')
    op.add_column('onboarding_states', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('onboarding_states', sa.Column('daily_commitment', sa.String(), nullable=True))
    op.add_column('onboarding_states', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('onboarding_states', sa.Column('weak_areas', sa.JSON(), nullable=True))
    op.add_column('onboarding_states', sa.Column('adventure_path', sa.String(), nullable=True))
    op.add_column('onboarding_states', sa.Column('selected_attributes', sa.JSON(), nullable=True))
    op.add_column('onboarding_states', sa.Column('character_name', sa.String(), nullable=True))
    op.add_column('onboarding_states', sa.Column('playstyle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_states', 'playstyle')
    op.drop_column('onboarding_states', 'character_name')
    op.drop_column('onboarding_states', 'selected_attributes')
    op.drop_column('onboarding_states', 'adventure_path')
    op.drop_column('onboarding_states', 'weak_areas')
    op.drop_column('onboarding_states', 'difficulty')
    op.drop_column('onboarding_states', 'daily_commitment')
    op.drop_column('onboarding_states', 'deadline')
    op.add_column('characters', sa.Column('pathName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'adventure_path')
    # ### end Alembic commands ###
